### ISSUE TITLE
What's the benefit of using Hapi.js plugins?

### ISSUE THREAD

**Issue by minustime** [johnbrett/hapi-level-sample#2]
The code seems more organized when using Hapi plugins. I'm just curious what the benefits are besides the obvious logical organization. Also, how do you know when to split your code into plugins? Thanks!

**Comment by ignivaravinderrikhi** [comment]
Are there any performance issues in **plugin** based **module loading** as compared to any normal **require** based **module loading**  ??

**Comment by johnbrett** [comment]
The only issue I'm aware of is if you use `server.expose(obj)`: https://hapijs.com/api#-serverexposeobj on a deeply nested object, it can be quite slow as it does a full object clone which is expensive at startup time (https://github.com/hapijs/hapi/issues/3126).

For this situation, I'd would just expose the required values: `https://hapijs.com/api#-serverexposekey-value`: https://hapijs.com/api#-serverexposekey-value
