### ISSUE TITLE
Breaks when using a newer version of Calibrate

### ISSUE THREAD

**Issue by reedog117** [johnbrett/hapi-level-sample#3]
I tried adapting the sample code to a project I'm working on, and found that my code wasn't working right due to changes between 0.0.x (which is what is currently in package.json) and 2.0.1 (the current version).  I'm thinking this sample needs to be updated to conform to the new Calibrate syntax if the dependencies are to be updated.

**Comment by johnbrett** [comment]
Hey Patrick! Will update this, thanks for pointing it out!

**Comment by johnbrett** [comment]
@reedog117 I've updated the project to use the latest version of Calibrate. If you've any questions, or an example you'd like this project to cover please let me know :)
